// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	comments "news-app-be23/internal/features/comments"

	mock "github.com/stretchr/testify/mock"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// DeleteComment provides a mock function with given fields: id
func (_m *Services) DeleteComment(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllComments provides a mock function with given fields:
func (_m *Services) GetAllComments() ([]comments.Comment, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllComments")
	}

	var r0 []comments.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]comments.Comment, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []comments.Comment); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]comments.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertComment provides a mock function with given fields: newComment
func (_m *Services) InsertComment(newComment comments.Comment) error {
	ret := _m.Called(newComment)

	if len(ret) == 0 {
		panic("no return value specified for InsertComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(comments.Comment) error); ok {
		r0 = rf(newComment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServices creates a new instance of Services. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
